modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="clickmachine" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Click Machine" #mandatory

description='''
Clicc.
'''

[[dependencies.clickmachine]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.clickmachine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clickmachine]]
    modId="placebo"
    mandatory=true
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"